include: package:lint/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint

linter:
  rules:
    unawaited_futures: true
    sort_pub_dependencies: false