include: package:lint/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "lib/generated/**"
  plugins:
    - custom_lint

linter:
  rules:
    unawaited_futures: true
    sort_pub_dependencies: false