synthetic-package: false
arb-dir: lib/src/presentation/common/l10n/arb
output-dir: lib/src/presentation/common/l10n/arb
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
